### ISSUE TITLE
book synopsis should be TEXT

### ISSUE THREAD

**Issue by abdelhalimjean** [ali-bouali/book-social-network#3]
when trying to add a new book and we write a long synopsis (>255 characters) we'll get an "value too long for type character varying(255)" error

using a column type TEXT would be better in this case since a synopsis can be a few paragraphs

**Comment by ali-bouali** [comment]
true. please feel free to adjust.
What I mentioned is just an example and you have all the freedom to extend the application and do all the changes that suits you.
Happy you made it this far. Keep going
